/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_launcher2_jni_ImageUtils */

#ifndef _Included_com_android_launcher3_jni_ImageUtils
#define _Included_com_android_launcher3_jni_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_launcher3_jni_ImageUtils
 * Method:    nativeToBlur
 * Signature: (Landroid/graphics/Bitmap;Landroid/graphics/Bitmap;I)V
 */
JNIEXPORT void JNICALL Java_com_android_launcher3_jni_ImageUtils_nativeToBlur
  (JNIEnv *, jclass, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
